/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  DEFAULT_SETTINGS: () => DEFAULT_SETTINGS,
  default: () => ChatMemoPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/ChatModal.ts
var import_obsidian2 = require("obsidian");

// src/utils.ts
function parseBubble(raw) {
  const t = raw.trim();
  const h3 = t.match(/^###\s+(.+)/);
  if (h3)
    return { side: "other", type: "h3", content: h3[1].trim(), raw };
  const h2 = t.match(/^##\s+(.+)/);
  if (h2)
    return { side: "other", type: "h2", content: h2[1].trim(), raw };
  const h1 = t.match(/^#\s+(.+)/);
  if (h1)
    return { side: "other", type: "h1", content: h1[1].trim(), raw };
  const done = t.match(/^[-*]\s+\[x\]\s+(.*)/i);
  if (done)
    return { side: "other", type: "done", content: done[1].trim(), raw };
  const todo = t.match(/^[-*]\s+\[ \]\s+(.*)/);
  if (todo)
    return { side: "other", type: "todo", content: todo[1].trim(), raw };
  const bullet = t.match(/^[-*]\s+(.+)/);
  if (bullet)
    return { side: "other", type: "bullet", content: bullet[1].trim(), raw };
  if (/^\[\[.+\]\]$/.test(t)) {
    return { side: "other", type: "backlink", content: t.slice(2, -2), raw };
  }
  if (/^(#\S+\s*)+$/.test(t)) {
    return { side: "other", type: "tag", content: t, raw };
  }
  return { side: "self", type: "text", content: t, raw };
}
function nowTime() {
  return new Date().toLocaleTimeString("ko-KR", {
    hour: "2-digit",
    minute: "2-digit",
    hour12: false
  });
}
function todayDate() {
  return new Date().toISOString().split("T")[0];
}
function sanitizeFilename(name) {
  return name.replace(/[\\/:*?"<>|]/g, "_").trim();
}

// src/SaveModal.ts
var import_obsidian = require("obsidian");
var SaveModal = class extends import_obsidian.Modal {
  constructor(app, plugin, bubbles, isClose = false, onSaved) {
    super(app);
    this.plugin = plugin;
    this.bubbles = bubbles;
    this.isClose = isClose;
    this.onSaved = onSaved;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("chat-memo-save-modal");
    contentEl.createEl("h2", { text: this.isClose ? "\uBA54\uBAA8 \uB2EB\uAE30" : "\uBA54\uBAA8 \uC800\uC7A5" });
    if (this.bubbles.length > 0) {
      contentEl.createEl("p", {
        text: `${this.bubbles.length}\uAC1C\uC758 \uBA54\uBAA8\uB97C Obsidian \uB178\uD2B8\uB85C \uC800\uC7A5\uD569\uB2C8\uB2E4.`,
        cls: "cm-modal-desc"
      });
      const { autoTags, autoLinks } = this.extractMeta();
      if (autoTags.length || autoLinks.length) {
        const preview = contentEl.createDiv("cm-meta-preview");
        if (autoTags.length)
          preview.createEl("span", { text: `\u{1F3F7}\uFE0F ${autoTags.join("  ")}`, cls: "cm-meta-chip" });
        if (autoLinks.length)
          preview.createEl("span", { text: `\u{1F517} ${autoLinks.map((l) => `[[${l}]]`).join("  ")}`, cls: "cm-meta-chip" });
      }
      const titleWrap = contentEl.createDiv("cm-field");
      titleWrap.createEl("label", { text: "\uB178\uD2B8 \uC81C\uBAA9" });
      const titleInput = titleWrap.createEl("input", {
        type: "text",
        placeholder: "\uBE44\uC6CC\uB450\uBA74 \uB0A0\uC9DC\uB85C \uC800\uC7A5"
      });
      titleInput.style.width = "100%";
      const tagWrap = contentEl.createDiv("cm-field");
      tagWrap.createEl("label", { text: "\uCD94\uAC00 \uD0DC\uADF8 (\uC27C\uD45C \uAD6C\uBD84, #\uC5C6\uC774 \uC785\uB825)" });
      const tagInput = tagWrap.createEl("input", {
        type: "text",
        placeholder: "\uC608: \uBA54\uBAA8, \uD560\uC77C"
      });
      tagInput.style.width = "100%";
      const btnRow = contentEl.createDiv("cm-btn-row");
      if (this.isClose) {
        btnRow.createEl("button", { text: "\uC800\uC7A5\uD558\uC9C0 \uC54A\uACE0 \uB2EB\uAE30" }).addEventListener("click", () => {
          if (this.onSaved)
            this.onSaved();
          this.close();
        });
      } else {
        btnRow.createEl("button", { text: "\uCDE8\uC18C" }).addEventListener("click", () => this.close());
      }
      const saveBtn = btnRow.createEl("button", { text: "\uC800\uC7A5", cls: "mod-cta" });
      saveBtn.addEventListener("click", async () => {
        await this.save(titleInput.value.trim(), tagInput.value.trim());
        if (this.onSaved)
          this.onSaved();
        this.close();
      });
      titleInput.addEventListener("keydown", (e) => {
        if (e.key === "Enter")
          saveBtn.click();
      });
      setTimeout(() => titleInput.focus(), 50);
    } else {
      contentEl.createEl("p", { text: "\uC800\uC7A5\uD560 \uBA54\uBAA8\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4.", cls: "cm-modal-desc" });
      const closeBtn = contentEl.createEl("button", { text: "\uB2EB\uAE30", cls: "mod-cta" });
      closeBtn.style.width = "100%";
      closeBtn.addEventListener("click", () => {
        if (this.onSaved)
          this.onSaved();
        this.close();
      });
    }
    if (this.isClose) {
      contentEl.createEl("hr", { cls: "cm-modal-hr" });
      const row = contentEl.createDiv("cm-autoopen-row");
      const toggle = row.createEl("input", { type: "checkbox" });
      toggle.checked = this.plugin.settings.autoOpen;
      row.createEl("label", { text: "\uB2E4\uC74C\uC5D0 Obsidian \uC5F4 \uB54C \uC790\uB3D9\uC73C\uB85C \uD31D\uC5C5 \uC5F4\uAE30" });
      toggle.addEventListener("change", async () => {
        this.plugin.settings.autoOpen = toggle.checked;
        await this.plugin.saveSettings();
      });
    }
  }
  /** 버블에서 태그·백링크 자동 추출 */
  extractMeta() {
    var _a;
    const autoTags = [];
    const autoLinks = [];
    for (const b of this.bubbles) {
      if (b.type === "tag") {
        const tags = (_a = b.content.match(/#\S+/g)) != null ? _a : [];
        tags.forEach((t) => autoTags.push(t));
      }
      if (b.type === "backlink") {
        autoLinks.push(b.content);
      }
    }
    return { autoTags, autoLinks };
  }
  async save(title, extraTagStr) {
    const date = todayDate();
    const time = nowTime();
    const finalTitle = title || date;
    const filename = sanitizeFilename(title ? title : date);
    const { autoTags, autoLinks } = this.extractMeta();
    const extraTags = extraTagStr ? extraTagStr.split(",").map((t) => t.trim().replace(/^#/, "")).filter(Boolean) : [];
    const allTagsRaw = [
      ...autoTags.map((t) => t.replace(/^#/, "")),
      ...extraTags
    ];
    const allTags = [...new Set(allTagsRaw)];
    const frontmatter = [
      "---",
      `date: ${date}`,
      allTags.length ? `tags: [${allTags.join(", ")}]` : null,
      autoLinks.length ? `links: [${autoLinks.map((l) => `"[[${l}]]"`).join(", ")}]` : null,
      "---",
      ""
    ].filter((l) => l !== null).join("\n");
    const metaLines = [];
    metaLines.push(`> [!info] \uBA54\uBAA8 \uC815\uBCF4`);
    metaLines.push(`> - \u{1F4C5} **\uC791\uC131\uC77C**: ${date} ${time}`);
    if (allTags.length)
      metaLines.push(`> - \u{1F3F7}\uFE0F **\uD0DC\uADF8**: ${allTags.map((t) => `#${t}`).join("  ")}`);
    if (autoLinks.length)
      metaLines.push(`> - \u{1F517} **\uBC31\uB9C1\uD06C**: ${autoLinks.map((l) => `[[${l}]]`).join("  ")}`);
    const metaBlock = metaLines.join("\n") + "\n\n";
    const rawLines = this.bubbles.filter((b) => b.type !== "tag" && b.type !== "backlink").map((b) => {
      switch (b.type) {
        case "h1":
          return `# ${b.content}`;
        case "h2":
          return `## ${b.content}`;
        case "h3":
          return `### ${b.content}`;
        case "bullet":
          return `- ${b.content}`;
        case "todo":
          return `- [ ] ${b.content}`;
        case "done":
          return `- [x] ${b.content}`;
        default:
          return `- ${b.content}`;
      }
    });
    const formattedLines = [];
    for (let i = 0; i < rawLines.length; i++) {
      const line = rawLines[i];
      const isHeading = /^#{1,3} /.test(line);
      if (isHeading && i > 0) {
        formattedLines.push("");
      }
      formattedLines.push(line);
    }
    const hasH1 = rawLines.some((l) => l.startsWith("# "));
    const bodyHeading = hasH1 ? "" : `# ${finalTitle}

`;
    const body = bodyHeading + formattedLines.join("\n") + "\n";
    const content = frontmatter + metaBlock + body;
    try {
      const path = `${filename}.md`;
      const existing = this.app.vault.getAbstractFileByPath(path);
      let savedFile;
      if (existing instanceof import_obsidian.TFile) {
        const old = await this.app.vault.read(existing);
        await this.app.vault.modify(existing, old + "\n\n---\n\n" + metaBlock + body);
        new import_obsidian.Notice(`\uAE30\uC874 \uB178\uD2B8\uC5D0 \uCD94\uAC00\uB428: ${path}`);
        savedFile = existing;
      } else {
        savedFile = await this.app.vault.create(path, content);
        new import_obsidian.Notice(`\uC800\uC7A5 \uC644\uB8CC: ${path}`);
      }
      const leaf = this.app.workspace.getLeaf(false);
      await leaf.openFile(savedFile);
    } catch (err) {
      new import_obsidian.Notice("\uC800\uC7A5 \uC2E4\uD328: " + err.message);
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/ChatModal.ts
var ChatModal = class extends import_obsidian2.Modal {
  constructor(plugin) {
    super(plugin.app);
    this.bubbles = [];
    this.plugin = plugin;
    this.modalEl.addClass("chat-memo-modal");
    this.scope.register([], "Escape", () => {
      this.requestClose();
      return false;
    });
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("chat-memo-root");
    const toolbar = contentEl.createDiv("cm-toolbar");
    toolbar.createEl("span", { text: "Chat Memo", cls: "cm-toolbar-title" });
    this.mdToggleBtn = toolbar.createEl("button", {
      cls: "cm-toolbar-btn cm-md-toggle",
      attr: { title: "\uB9C8\uD06C\uB2E4\uC6B4 \uBAA8\uB4DC ON/OFF" }
    });
    this.updateMdToggleBtn();
    this.mdToggleBtn.addEventListener("click", async () => {
      this.plugin.settings.markdownMode = !this.plugin.settings.markdownMode;
      await this.plugin.saveSettings();
      this.updateMdToggleBtn();
      this.updateStatusBar();
    });
    toolbar.createEl("button", {
      text: "\u{1F5D1}",
      cls: "cm-toolbar-btn",
      attr: { title: "\uC804\uCCB4 \uC9C0\uC6B0\uAE30" }
    }).addEventListener("click", () => {
      if (!this.bubbles.length)
        return;
      this.bubbles = [];
      this.chatEl.empty();
    });
    toolbar.createEl("button", {
      text: "\u{1F4BE}",
      cls: "cm-toolbar-btn",
      attr: { title: "\uC800\uC7A5" }
    }).addEventListener("click", () => {
      new SaveModal(this.app, this.plugin, this.bubbles, false, () => {
        this.bubbles = [];
        if (this.chatEl)
          this.chatEl.empty();
      }).open();
    });
    this.statusBar = contentEl.createDiv("cm-status-bar");
    this.updateStatusBar();
    this.chatEl = contentEl.createDiv("cm-chat");
    const hint = this.chatEl.createDiv("cm-hint");
    hint.innerHTML = [
      "<b># \uC81C\uBAA9</b> / <b>## \uC18C\uC81C\uBAA9</b> / <b>### \uC18C\uC18C\uC81C\uBAA9</b>",
      "<b>- \uD56D\uBAA9</b> \xB7 <b>- [ ] \uD560\uC77C</b> \xB7 <b>- [x] \uC644\uB8CC</b>",
      "<b>[[\uBC31\uB9C1\uD06C]]</b> \xB7 <b>#\uD0DC\uADF8</b>",
      "\u2192 \uC67C\uCABD \uBC84\uBE14 &nbsp;|&nbsp; \uC77C\uBC18 \uD14D\uC2A4\uD2B8 \u2192 \uC624\uB978\uCABD \uBC84\uBE14"
    ].join("<br>");
    const inputArea = contentEl.createDiv("cm-input-area");
    this.inputEl = inputArea.createEl("textarea", {
      cls: "cm-input",
      attr: { placeholder: "\uBA54\uBAA8 \uC785\uB825\u2026 (Enter \uC804\uC1A1 / Shift+Enter \uC904\uBC14\uAFC8)" }
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.submit();
      }
    });
    this.inputEl.addEventListener("input", () => {
      this.inputEl.style.height = "auto";
      this.inputEl.style.height = Math.min(this.inputEl.scrollHeight, 140) + "px";
    });
    inputArea.createEl("button", { text: "\uC804\uC1A1", cls: "cm-send-btn" }).addEventListener("click", () => this.submit());
    setTimeout(() => this.inputEl.focus(), 50);
  }
  requestClose() {
    if (this.bubbles.length > 0) {
      new SaveModal(this.app, this.plugin, this.bubbles, true, () => {
        this.bubbles = [];
        this.close();
      }).open();
    } else {
      this.close();
    }
  }
  updateMdToggleBtn() {
    const on = this.plugin.settings.markdownMode;
    this.mdToggleBtn.textContent = on ? "#\uFE0F\u20E3" : "\u270F\uFE0F";
    this.mdToggleBtn.title = on ? "\uB9C8\uD06C\uB2E4\uC6B4 \uBAA8\uB4DC ON (\uD074\uB9AD\uD574\uC11C \uB044\uAE30)" : "\uB9C8\uD06C\uB2E4\uC6B4 \uBAA8\uB4DC OFF (\uD074\uB9AD\uD574\uC11C \uCF1C\uAE30)";
    this.mdToggleBtn.toggleClass("cm-md-toggle--on", on);
    this.mdToggleBtn.toggleClass("cm-md-toggle--off", !on);
  }
  updateStatusBar() {
    this.statusBar.empty();
    const on = this.plugin.settings.markdownMode;
    this.statusBar.createEl("span", {
      text: on ? "\u2726 \uB9C8\uD06C\uB2E4\uC6B4 \uBAA8\uB4DC ON \u2014 # / - / [[]] / #\uD0DC\uADF8 \u2192 \uC67C\uCABD \uBC84\uBE14" : "\u270F\uFE0F \uC77C\uBC18 \uBAA8\uB4DC \u2014 \uBAA8\uB4E0 \uC785\uB825\uC774 \uC624\uB978\uCABD(\uBCF8\uC778) \uBC84\uBE14",
      cls: on ? "cm-status--on" : "cm-status--off"
    });
  }
  submit() {
    var _a;
    const raw = this.inputEl.value;
    if (!raw.trim())
      return;
    (_a = this.chatEl.querySelector(".cm-hint")) == null ? void 0 : _a.remove();
    const info = this.plugin.settings.markdownMode ? parseBubble(raw) : { side: "self", type: "text", content: raw.trim(), raw };
    this.bubbles.push(info);
    this.renderBubble(info);
    this.inputEl.value = "";
    this.inputEl.style.height = "auto";
    this.chatEl.scrollTop = this.chatEl.scrollHeight;
  }
  renderBubble(info) {
    var _a;
    const time = nowTime();
    const row = this.chatEl.createDiv(`cm-row cm-row--${info.side}`);
    if (info.side === "other") {
      row.createDiv("cm-avatar").textContent = "\u2726";
    }
    const bubble = row.createDiv(
      `cm-bubble cm-bubble--${info.side} cm-bubble--${info.type}`
    );
    switch (info.type) {
      case "h1":
        bubble.createEl("h1", { text: info.content, cls: "cm-heading" });
        break;
      case "h2":
        bubble.createEl("h2", { text: info.content, cls: "cm-heading" });
        break;
      case "h3":
        bubble.createEl("h3", { text: info.content, cls: "cm-heading" });
        break;
      case "bullet": {
        const w = bubble.createDiv("cm-bullet-wrap");
        w.createEl("span", { text: "\u2022", cls: "cm-bullet-icon" });
        w.createEl("span", { text: info.content });
        break;
      }
      case "todo": {
        const w = bubble.createDiv("cm-bullet-wrap");
        w.createEl("span", { text: "\u2610", cls: "cm-checkbox cm-checkbox--unchecked" });
        w.createEl("span", { text: info.content, cls: "cm-todo-text" });
        break;
      }
      case "done": {
        const w = bubble.createDiv("cm-bullet-wrap");
        w.createEl("span", { text: "\u2611", cls: "cm-checkbox cm-checkbox--checked" });
        w.createEl("span", { text: info.content, cls: "cm-done-text" });
        break;
      }
      case "tag":
        ((_a = info.content.match(/#\S+/g)) != null ? _a : [info.content]).forEach(
          (tag) => bubble.createEl("span", { text: tag, cls: "cm-tag-badge" })
        );
        break;
      case "backlink": {
        const link = bubble.createEl("span", { cls: "cm-backlink" });
        link.createEl("span", { text: "[[", cls: "cm-backlink-brackets" });
        link.createEl("span", { text: info.content, cls: "cm-backlink-text" });
        link.createEl("span", { text: "]]", cls: "cm-backlink-brackets" });
        break;
      }
      default:
        bubble.textContent = info.content;
    }
    row.createEl("span", { text: time, cls: "cm-time" });
  }
  /** Obsidian 기본 X(닫기) 버튼도 저장 흐름으로 처리 */
  close() {
    if (this.bubbles.length > 0) {
      new SaveModal(this.app, this.plugin, this.bubbles, true, () => {
        this.bubbles = [];
        super.close();
      }).open();
    } else {
      super.close();
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  markdownMode: true,
  autoOpen: true
};
var ChatMemoPlugin = class extends import_obsidian3.Plugin {
  constructor(app, manifest) {
    super(app, manifest);
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ChatMemoSettingTab(this.app, this));
    this.addRibbonIcon("message-square", "Chat Memo \uC5F4\uAE30", () => {
      new ChatModal(this).open();
    });
    this.addCommand({
      id: "open-chat-memo",
      name: "Chat Memo \uD31D\uC5C5 \uC5F4\uAE30",
      callback: () => new ChatModal(this).open()
    });
    this.addCommand({
      id: "toggle-markdown-mode",
      name: "\uB9C8\uD06C\uB2E4\uC6B4 \uBAA8\uB4DC ON/OFF \uD1A0\uAE00",
      callback: async () => {
        this.settings.markdownMode = !this.settings.markdownMode;
        await this.saveSettings();
      }
    });
    if (this.settings.autoOpen) {
      this.app.workspace.onLayoutReady(() => {
        new ChatModal(this).open();
      });
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var ChatMemoSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Chat Memo \uC124\uC815" });
    new import_obsidian3.Setting(containerEl).setName("\uC2DC\uC791 \uC2DC \uC790\uB3D9\uC73C\uB85C \uD31D\uC5C5 \uC5F4\uAE30").setDesc("Obsidian\uC744 \uC5F4 \uB54C Chat Memo \uD31D\uC5C5\uC774 \uC790\uB3D9\uC73C\uB85C \uB098\uD0C0\uB0A9\uB2C8\uB2E4. OFF \uC2DC Obsidian\uC774 \uC815\uC0C1\uC801\uC73C\uB85C \uC5F4\uB9BD\uB2C8\uB2E4.").addToggle(
      (t) => t.setValue(this.plugin.settings.autoOpen).onChange(async (v) => {
        this.plugin.settings.autoOpen = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\uB9C8\uD06C\uB2E4\uC6B4 \uBAA8\uB4DC").setDesc("# \uC81C\uBAA9, - \uD56D\uBAA9, - [ ] \uD560\uC77C, [[\uBC31\uB9C1\uD06C]], #\uD0DC\uADF8 \u2192 \uC67C\uCABD(\uC0C1\uB300\uBC29) \uBC84\uBE14\uB85C \uD45C\uC2DC\uD569\uB2C8\uB2E4.").addToggle(
      (t) => t.setValue(this.plugin.settings.markdownMode).onChange(async (v) => {
        this.plugin.settings.markdownMode = v;
        await this.plugin.saveSettings();
      })
    );
  }
};
